spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:13306/multi_demo?serverTimeZone=Asia/Seoul&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: root
    password: root
  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: true
